services:
  auth-db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: users
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
